---

## Install Nextcloud docker
- name: Install nextcloud docker
  template:
    src: nextcloud.yaml.j2
    dest: /home/docker/nextcloud.yaml
    owner: root
    group: root
    mode: 0400
  notify: 
    - start nextcloud docker
    - set trusted domain
    - overwrite protocol

## Install Nextcloud backup docker
- name: Install nextcloud backup compose file
  template:
    src: backup.yaml.j2
    dest: /home/docker/backups/backup-nextcloud.yaml
    owner: root
    group: root
    mode: 0400

- name: Copy docker file for mysql duplicity
  copy:
    src: Dockerfile
    dest: /home/docker/backups/Dockerfile-nextbak
    owner: root
    group: root
    mode: 0644

- name: add cron job to run backup every week
  cron:
    name: backup nextcloud
    minute: 43
    hour: 2
    weekday: 7
    job: /usr/local/bin/docker-compose -f /home/docker/backups/backup-nextcloud.yaml run --rm backup_nextcloud 
