---

- name: start nextcloud docker
  docker_service:
    project_src: /home/docker/
    files: nextcloud.yaml
    project_name: nextcloud
  async: 120
  poll: 10
  when: not ansible_check_mode

- name: set trusted domain
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" trusted_domains 1 --value="{{ cloud_url }}"

- name: overwrite protocol
  shell: docker exec -u www-data nextcloud php occ --no-warnings "config:system:set" overwriteprotocol --value="https"
